apiVersion: apps/v1
kind: Deployment
metadata:
  name: factored-scraper
spec:
  replicas: 20  # Adjusted based on 10 nodes and 2 pods per node
  selector:
    matchLabels:
      app: factored-scraper
  template:
    metadata:
      labels:
        app: factored-scraper
    spec:
      containers:
        - name: factored-scraper
          image: factored-scraper:1.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"  # Adjusted based on Docker Compose
            limits:
              cpu: "1"
              memory: "1Gi"  # Adjusted based on Docker Compose
      # Optionally add node affinity or tolerations here if needed
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #       - matchExpressions:
      #           - key: <key>
      #             operator: In
      #             values:
      #               - <value>
