[theme]
primaryColor="#a7dcb2"
backgroundColor="#101010"
secondaryBackgroundColor="#3a7658"
textColor="#ffffff"


## Hex Color Code ## 
####################
##   #032107      ##
##   #235434      ##
##   #3a7658      ##
##   #a7dcb2      ##
##   #81be4d      ##
